import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {createWorker} from '../worker.mjs';import {makePasswordRecord} from '../auth.mjs';import {random,validateContent,decodeAsset} from '../common.mjs';import {LocalStore,sqliteBinding} from '../local-support.mjs';import {GitHubStore} from '../github.mjs';
const password='Local-test-only-password-2026!';const origin='https://admin.example.workers.dev';const source=path.resolve(import.meta.dirname,'../..');
async function fixture(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'gio-auth-test-'));fs.mkdirSync(path.join(dir,'content'));fs.mkdirSync(path.join(dir,'uploads'));fs.copyFileSync(path.join(source,'content/site.json'),path.join(dir,'content/site.json'));const db=sqliteBinding();t.after(()=>{db.close();fs.rmSync(dir,{recursive:true,force:true});});const pepper=random();const env={ADMIN_USERNAME:'admin',AUTH_PEPPER:pepper,PASSWORD_RECORD:await makePasswordRecord(password,pepper),AUTH_DB:db,GITHUB_BRANCH:'main',GITHUB_REPO:'test/fixture'};const store=new LocalStore(dir);const app=createWorker(()=>store);
 const call=(route,body,headers={})=>app.fetch(new Request(origin+route,{method:body===undefined?'GET':'POST',headers:{...(body===undefined?{}:{'Content-Type':'application/json',Origin:origin}),...headers},body:body===undefined?undefined:JSON.stringify(body)}),env);
 const login=async()=>{const r=await call('/api/login',{username:'admin',password});assert.equal(r.status,200);const data=await r.json();return {cookie:r.headers.get('set-cookie').split(';')[0],csrf:data.csrf,headers:{Cookie:r.headers.get('set-cookie').split(';')[0],'X-CSRF-Token':data.csrf},response:r};};return {dir,db,env,store,call,login};}
test('unauthenticated writes, forged sessions and foreign-origin login are rejected',async t=>{const f=await fixture(t);assert.equal((await f.call('/api/v1',{action:'persistEntry'})).status,401);assert.equal((await f.call('/api/session',undefined,{Cookie:'__Host-gio_session='+'a'.repeat(64)})).status,401);assert.equal((await f.call('/api/login',{username:'admin',password},{Origin:'https://evil.example'})).status,403);});
test('password validation, secure cookie, CSRF and server-side logout revocation',async t=>{const f=await fixture(t);assert.equal((await f.call('/api/login',{username:'admin',password:'wrong'})).status,401);const s=await f.login();const c=s.response.headers.get('set-cookie');for(const flag of ['HttpOnly','Secure','SameSite=Strict','__Host-'])assert.ok(c.includes(flag));assert.equal((await f.call('/api/session',undefined,{Cookie:s.cookie})).status,200);assert.equal((await f.call('/api/v1',{action:'info'},{Cookie:s.cookie})).status,403);assert.equal((await f.call('/api/logout',{},s.headers)).status,200);assert.equal((await f.call('/api/session',undefined,{Cookie:s.cookie})).status,401);});
test('password rotation and session expiration revoke access',async t=>{const f=await fixture(t);const s=await f.login();f.env.AUTH_PEPPER=random();assert.equal((await f.call('/api/session',undefined,{Cookie:s.cookie})).status,401);const g=await fixture(t);const a=await g.login();g.db.db.exec('UPDATE sessions SET expires = 0');assert.equal((await g.call('/api/session',undefined,{Cookie:a.cookie})).status,401);});
test('sixth login attempt is blocked by a persistent atomic rate limit',async t=>{const f=await fixture(t);for(let i=0;i<5;i++)assert.equal((await f.call('/api/login',{username:'admin',password:'bad'})).status,401);assert.equal((await f.call('/api/login',{username:'admin',password})).status,429);});
test('content save and upload work together; stale revision cannot overwrite',async t=>{const f=await fixture(t);const s=await f.login();const read=await(await f.call('/api/v1',{action:'getEntry',params:{path:'content/site.json'}},s.headers)).json();const d=JSON.parse(read.data);d.title='Changed safely';const png=fs.readFileSync(path.join(source,'logo.png')).toString('base64');const payload={action:'persistEntry',revision:read.file.id,params:{dataFiles:[{path:'content/site.json',raw:JSON.stringify(d)}],assets:[{path:'uploads/test.png',content:png,encoding:'base64'}]}};const result=await f.call('/api/v1',payload,s.headers);assert.equal(result.status,200);assert.equal(JSON.parse(fs.readFileSync(path.join(f.dir,'content/site.json'))).title,'Changed safely');assert.ok(fs.existsSync(path.join(f.dir,'uploads/test.png')));assert.equal((await f.call('/api/v1',payload,s.headers)).status,409);});
test('API cannot write source code, other branches, renamed entries or invalid content',async t=>{const f=await fixture(t);const s=await f.login();for(const payload of [{action:'getEntry',params:{path:'../.secrets/local.json'}},{action:'getEntry',branch:'other',params:{path:'content/site.json'}},{action:'persistEntry',params:{dataFiles:[{path:'index.html',raw:'hacked'}]}},{action:'persistEntry',params:{dataFiles:[{path:'content/site.json',newPath:'index.html',raw:'{}'}]}},{action:'deleteFile',params:{path:'content/site.json'}}])assert.equal((await f.call('/api/v1',payload,s.headers)).status,403);const bad={action:'persistEntry',params:{dataFiles:[{path:'content/site.json',raw:'{}'}]}};assert.equal((await f.call('/api/v1',bad,s.headers)).status,400);});
test('media metadata, upload size/type checks and referenced-file deletion guard',async t=>{const f=await fixture(t);const s=await f.login();const png=fs.readFileSync(path.join(source,'logo.png')).toString('base64');const asset={path:'uploads/test.png',content:png,encoding:'base64'};assert.equal((await f.call('/api/v1',{action:'persistMedia',params:{asset}},s.headers)).status,200);assert.equal((await f.call('/api/v1',{action:'persistMedia',params:{asset}},s.headers)).status,409);const list=await(await f.call('/api/v1',{action:'getMedia',params:{mediaFolder:'uploads'}},s.headers)).json();assert.equal(list[0].name,'test.png');assert.equal((await f.call(list[0].url,undefined,{Cookie:s.cookie})).headers.get('content-type'),'image/png');const file=path.join(f.dir,'content/site.json');const d=JSON.parse(fs.readFileSync(file));d.logo='/uploads/test.png';fs.writeFileSync(file,JSON.stringify(d));assert.equal((await f.call('/api/v1',{action:'deleteFile',params:{path:asset.path}},s.headers)).status,409);d.logo='/logo.png';fs.writeFileSync(file,JSON.stringify(d));assert.equal((await f.call('/api/v1',{action:'deleteFile',params:{path:asset.path}},s.headers)).status,200);assert.throws(()=>decodeAsset({...asset,content:Buffer.from('<script>bad</script>').toString('base64')}));assert.throws(()=>decodeAsset({...asset,path:'uploads/test.svg'}));assert.throws(()=>decodeAsset({...asset,content:'A'.repeat(8*1024*1024)}));});
test('content validation blocks script URLs and duplicate sections',()=>{const d=JSON.parse(fs.readFileSync(path.join(source,'content/site.json')));d.logo='javascript:alert(1)';assert.throws(()=>validateContent(JSON.stringify(d)));d.logo='/logo.png';d.layout.sections[1].id=d.layout.sections[0].id;assert.throws(()=>validateContent(JSON.stringify(d)));});
test('GitHub writes an atomic tree and uses non-forced reference update',async()=>{const calls=[];const store=new GitHubStore({GITHUB_REPO:'test/fixture',GITHUB_BRANCH:'main',GITHUB_TOKEN:'test-secret'},async(url,options)=>{calls.push({url,...options});const endpoint=new URL(url).pathname;return Response.json(endpoint.endsWith('/git/blobs')?{sha:'blob'}:endpoint.endsWith('/git/trees')?{sha:'tree'}:{sha:'commit'});});await store.commit([{path:'content/site.json',bytes:new TextEncoder().encode('{}')},{path:'uploads/file.png',bytes:new Uint8Array([1])}],{head:'parent',tree:'old-tree'},'Test');assert.equal(calls.filter(x=>x.url.endsWith('/git/commits')).length,1);assert.deepEqual(JSON.parse(calls.at(-1).body),{sha:'commit',force:false});assert.deepEqual(JSON.parse(calls.find(x=>x.url.endsWith('/git/commits')).body).parents,['parent']);assert.ok(calls.every(x=>x.headers.Authorization==='Bearer test-secret'));});
