import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import {createWorker} from '../backend/worker.mjs';import {LocalStore,sqliteBinding} from '../backend/local-support.mjs';
const repo=path.resolve(process.argv[2]||path.join(import.meta.dirname,'..'));
const project=path.resolve(import.meta.dirname,'..');const secretsPath=path.join(repo,'.secrets/local.json');
if(!fs.existsSync(secretsPath)){console.error('Chạy npm run admin:credentials -- --local trước để đặt mật khẩu local.');process.exit(1);}
const secrets=JSON.parse(fs.readFileSync(secretsPath,'utf8'));const db=sqliteBinding(path.join(repo,'.secrets/auth.sqlite'));
const mime={'.html':'text/html; charset=utf-8','.js':'application/javascript','.css':'text/css','.yml':'application/json','.json':'application/json','.txt':'text/plain'};
const env={ADMIN_USERNAME:'admin',GITHUB_REPO:'GioOTrongMat/GioOTrongMat.github.io',GITHUB_BRANCH:'main',...secrets,AUTH_DB:db,ASSETS:{async fetch(req){let name=new URL(req.url).pathname;if(name==='/')name='/index.html';if(!/^\/(index\.html|bootstrap\.js|login\.css|config\.yml|connection\.json|vendor\/decap-cms\.js(?:\.LICENSE\.txt)?)$/.test(name))return new Response('Not found',{status:404});try{return new Response(fs.readFileSync(path.join(project,'admin',name)),{headers:{'Content-Type':mime[path.extname(name)]||'text/plain'}});}catch{return new Response('Not found',{status:404});}}}};
const app=createWorker(()=>new LocalStore(repo));
http.createServer(async(req,res)=>{try{const host=req.headers.host;if(!['localhost:8787','127.0.0.1:8787'].includes(host)){res.writeHead(403);res.end();return;}const headers=new Headers();for(const[k,v]of Object.entries(req.headers))if(v)headers.set(k,Array.isArray(v)?v.join(','):v);headers.set('cf-connecting-ip',req.socket.remoteAddress||'local');const request=new Request('http://'+host+req.url,{method:req.method,headers,...(['GET','HEAD'].includes(req.method)?{}:{body:req,duplex:'half'})});const r=await app.fetch(request,env);res.writeHead(r.status,Object.fromEntries(r.headers));res.end(Buffer.from(await r.arrayBuffer()));}catch{res.writeHead(500);res.end('Local server error');}}).listen(8787,'127.0.0.1',()=>console.log('Admin username/password: http://localhost:8787 (local files only)'));
